### ISSUE TITLE
 The database manager has been disabled by the administrator

### ISSUE THREAD

**Issue by discapacidad5** [YunoHost-Apps/libreerp_ynh#28]
open  https://internet.noho.st/web/database/manager

mensenger: The database manager has been disabled by the administrator

**Comment by ashworksco** [comment]
I have the same issue. Can't log in.

**Comment by discapacidad5** [comment]
Edit etc/openerp-server.conf file

code: list_db = True

Then save ans restart openerp-server service.

This fixed the problem for me

**Comment by ashworksco** [comment]
@discapacidad5 I unfortunately do not see that in my /etc/ folder. 

I do see /etc/libreerp/main.conf, however.

I am getting an error when I install it requesting I install "psycopg2-binary":

/var/www/libreerp/venv/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: .
""")

**Comment by discapacidad5** [comment]
it is very likely that the file is with another place a long time ago that I did it and I don't remember exactly

What I am sure of is that it is the server.conf file that tries to locate them. show path is where all the server configurations are, such as the database password and the database address.

**Comment by ashworksco** [comment]
I checked the logs actually, and it looks like it's under /etc/libreerp/main.conf now. Thank you!
